sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
cache: cargo

script:
  - cargo test --features "hacl-star-resolver vector-tests" --verbose
  - cargo test --features "hacl-star-accelerated vector-tests" --verbose
  - cargo test --features "ring-resolver vector-tests" --verbose
  - cargo test --features "ring-accelerated vector-tests" --verbose

