[package]
name = "fuzz"
version = "0.1.0"
authors = ["Jake McGinty <me@jake.su>"]

[dependencies]
honggfuzz = { git = "https://github.com/mcginty/honggfuzz-rs", branch = "assert-unwind" }
snow = { path = "../" }
lazy_static = "*"